symlink:
  - .github/workflows/ci.yml: actions/ci.yml
  - .github/workflows/repo-setup.yml: actions/repo-setup.yml
  - README.md: README.tpl.md

ignore: [actions]

pre-run:
  - script: |
      // Use current dir as default for NPM package name
      process.env.NEAT_ASK_NPM_NAME = process.cwd().match(/\/([^/]*)$/)[1]

ask:
  - id: target_environment
    description: What environment is your package targeting?
    default:
      - Node.js: true
      - Browser: true
      - Vue.js: false
      - React: false
  - id: typescript
    description: Do you want to enable Typescript?
    default: [yes, no]
  - id: npm-builds
    description: On which operating systems do you want to test your build?
    replace: true
    default:
      - ubuntu-latest: true
      - windows-latest: true
      - macos-latest: true
  - id: package_name
    description: What is the name of your NPM package? (in the format 'name' or '@scope/name')
    replace: true
  - id: package_description
    replace: true
  - id: author_name
    replace: true
  - id: author_email
    replace: true
  - id: author_url
    replace: true
  - id: repository_name
    description: What is the name of your repository (in the format owner/repo)?
    replace: true
  - id: license
    default: Apache-2.0

post-run:
  - node configure.js
  - yarn install
